### PR TITLE
Just use window.animationWorklet for polyfill

### PR DESCRIPTION
**Pull request by majido**
Use window.animationWorklet for the polyfill so it is just a drop-in replacement.

Also move all animation startup logic to run once the addModule resolves.

### CODE REVIEW

**Comment by majido** [comment]
@flackr PTAL

**Comment by flackr** [comment]
Out of curiosity, why the ordering dependency? Does the real animation worklet not support lazily instantiating the animations after the script has loaded?

Technically it should be valid to instantiate the worklet animation prior to loading the animation worklet which animates it.

**Comment by majido** [comment]
AnimationWorklet should support lazily instantiating an animation after script load. Our current impl does not :cry:. So this makes the code as friendly as possible to *current* native impl in Chrome. But also it is a good practice IMHO. When possible I think it is a good idea to create and run animation after worklet script is loaded.

**Comment by majido** [comment]
Ping!

**Comment by flackr** [comment]
Okay, that's fine. I think that performance may be better if you don't wait, as you technically wouldn't need to round-trip through the main thread before your animation starts so heavy loading wouldn't have to delay animation start.

**Comment by majido** [comment]
Who can merge this?

**Comment by surma** [comment]
Sorry I haven’t gotten around to this sooner :)

**Pull request merged**
